version: '3.3'

x-logging: &default-logging
  driver: "fluentd"
  options:
    fluentd-address: "localhost:24224"
    fluentd-async-connect: "true"
    tag: "{{.Name}}-{{.ID}}"

services:

  placement:
    image: "daprio/placement:0.10.0"
    container_name: "placement"
    command: ["./placement", "-port", "6000"]
    volumes:
      - ./tools/docker-config/vault_dev_token:/vault/token
    ports:
      - "6000:6000"
    env_file:
      - .env
    logging: *default-logging

networks:
  default:
    external:
      name: burcin_network

