name: Build on push

on:
  push:
    branches:
    - master
  # - 'releases/**'
  # - '!releases/**-alpha'
    paths:
    - '.github/workflows/build_on_push.yml'
    - 'dist/**'
    # - '!test/**'
    # - '!docs/**'
    # - '!tools/**'
    # - '**/*.md'

defaults:
  run:
    shell: bash

jobs:

  build:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest

    env:
      #solution: '**/*.sln'
      #buildPlatform: 'Any CPU'
      #buildConfiguration: 'Release'
      buildNumber: '1.2'
      nuspecFile: './burcin.nuspec'
      assetPrefix: 'Burcin.Templates.CSharp'

    steps:
      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Set the build number
        run: echo "buildNumber=$buildNumber.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Set NuGet credentials
        shell: pwsh
        run: |
          ./tools/Set-NuGetCredentials.ps1 -ConfigFile ./nuget.config -Source github -Username ${{github.actor}} -Password ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: 'latest'

      - name: Pack
        run: nuget pack $nuspecFile -NonInteractive -OutputDirectory ./artifacts/packages -Verbosity Detailed -version $buildNumber
    #   run: dotnet pack -p:NuspecFile=<path to nuspec file> -p:NuspecProperties=<> -p:NuspecBasePath=<Base path>
    # # waiting for https://github.com/NuGet/Home/issues/4254

      - name: Publish artifacts (packages)
        uses: actions/upload-artifact@master
        with:
          name: packages
          path: ./artifacts/packages
          retention-days: 1

      - name: Publish artifacts (output)
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: output
          path: ./
          retention-days: 30

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{env.buildNumber}}
          release_name: ${{env.buildNumber}}
          draft: false
          prerelease: false
          body: |
            [Changelog](https://github.com/${{github.repository}}/blob/${{ steps.extract_branch.outputs.branch }}/CHANGELOG.md)

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/packages/${{env.assetPrefix}}.${{env.buildNumber}}.nupkg
          asset_name: ${{env.assetPrefix}}.${{env.buildNumber}}.nupkg
          asset_content_type: application/zip

      - name: Push to Nuget
        run: dotnet nuget push ./artifacts/packages/*.nupkg --skip-duplicate --source "nuget" --api-key ${NUGET_API_KEY}
        env:
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

      - name: Push to GitHub Packages
        run: dotnet nuget push ./artifacts/packages/*.nupkg --skip-duplicate --source "github" --api-key ${GITHUB_TOKEN} --no-symbols true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
